### ISSUE TITLE
question about train.py

### ISSUE THREAD

**Issue by ily666666** [dvlab-research/PFENet#34]
Why subtract one here (subcls-1)?
I understand subcls here is the index of class_chosen in sublist ,so it should  start from 0,but subtracting one cause it become a negative number
`        subcls = subcls[0].cpu().numpy()[0]
            class_intersection_meter[(subcls-1)%split_gap] += intersection[1]
            class_union_meter[(subcls-1)%split_gap] += union[1] `

**Comment by ily666666** [comment]
-1 % 1000 = 999

Is that the reason？

**Comment by tianzhuotao** [comment]
Uh...

This might be a part of the redundant code that I used previously, but it does not affect the final performance.

Sorry for the inconvenience.

**Comment by ily666666** [comment]
Thanks for your reply .You are a good man.Best wishes for a happy and prosperous future.Rencently I am confused about how to imporve the performance in few shot semantic segmentation .I read have read many papers ,and done lots of expriments ,But badly , in fact I doesn't make any progress so far.Next semester I will be a second year Postgraduate student,if I go on like this,I will loss the opportunity to practice in Internet companies.My lab only have one student,since I am the first student of my tutor ,I donnot have other classmates to communicate about it.And I only have one GPU which affects my speed.  I am very sad. I'm sorry for myself, I'm sorry for my teachers, I'm sorry for my parents.啊草

**Comment by ily666666** [comment]
So,please forgive me for being impolite. I have another question about  preprocessing  period. I noticed that your mean and std are  multiplied by  255 which described as value_scale, but img tensors are divided 255 and then normalized with mean and std ,[0.485, 0.456, 0.406] and [0.229, 0.224, 0.225] respectively, in other works. So, I want to know why .

**Comment by tianzhuotao** [comment]
@ily666666 Don't be disappointed in yourself, and I think the limited GPU resource is the main obstacle that inhibits your progress. I suggest you take an intern at a company with sufficient GPUs for conducting experiments where motivations originate.

As for your question, these two processes are actually identical (they both normalize the input images) since 255 exists in both numerator and denominator during the normalization process.

**Comment by ily666666** [comment]
Recently,I fonud that the test_num  of split 0 is 364.But in code you set est_num   to  5000.(Other splits are similar).
I want to know the meaning of this way. Why do you do repetitive test?

**Comment by ily666666** [comment]
ｈｅｌｌｏ

**Comment by Edithhhh** [comment]
> Thanks for your reply .You are a good man.Best wishes for a happy and prosperous future.Rencently I am confused about how to imporve the performance in few shot semantic segmentation .I read have read many papers ,and done lots of expriments ,But badly , in fact I doesn't make any progress so far.Next semester I will be a second year Postgraduate student,if I go on like this,I will loss the opportunits to practice in Internet companies.My lab only have one student,since I am the first student of my tutor ,I donnot have other classmates to communicate about it.And I only have one GPU which affects my speed. I am very sad. I'm sorry for myself, I'm sorry for my teachers, I'm sorry for my parents.啊草

大兄弟啊 加油！
