### ISSUE TITLE
Can you release pretrained models for other settings?

### ISSUE THREAD

**Issue by zhijiew** [dvlab-research/PFENet#42]
Thank you for your great work!

Can you release pretrained models of all settings? (VGG on PASCAL, ResNet101 on PASCAL ...)

**Comment by tianzhuotao** [comment]
@zhijiew 

Hi, thanks for your attention.

You can reproduce our results by modifying the provided config files.

For example, setting 'vgg' to true and 'layers' to 101 can reproduce the VGG and resnet-101 results respectively.

**Comment by zhijiew** [comment]
Thank you very much for your suggestions!
