### ISSUE TITLE
Colormap

### ISSUE THREAD

**Issue by joshmyersdean** [dvlab-research/PFENet#46]
Hello!

Thank you for this work. Could you provide the colormap you use to visualize segmentation results?

Thank you!

**Comment by tianzhuotao** [comment]
Thanks for being interested in our work.

We actually randomly chose the colors to visualize the results.

The implementation at: https://github.com/hszhao/semseg/blob/master/tool/test.py#L216 might be helpful.

**Comment by joshmyersdean** [comment]
Thank you!
