### ISSUE TITLE
Hi, I noticed that the script of this link was modified on 2021/6/21. Now I use this modified script to generate the label image of coco, which is different from that generated before. Is there something wrong with me or the modified script? Can you provide a previous version that you used before? Thanks!

### ISSUE THREAD

**Issue by zhangyuxuan321** [dvlab-research/PFENet#50]
Hi, I noticed that the script of this link was modified on 2021/6/21. Now I use this modified script to generate the label image of coco, which is different from that generated before. Is there something wrong with me or the modified script? Can you provide a previous version that you used before? Thanks!

_Originally posted by @JJ-res101 in https://github.com/dvlab-research/PFENet/issues/20#issuecomment-945080727_
Sorry,  I have the same promblem, could you please provide with the origin version? Thank u a lot.

**Comment by moonsh** [comment]
@zhangyuxuan321  The issue is solved?
