### ISSUE TITLE
PFE or PFE++

### ISSUE THREAD

**Issue by Ehteshamciitwah** [dvlab-research/PFENet#56]
Hello, thank you for your wonderful work in few shot segmentation.

I just want to confirm, is this repository implements PFE paper or the next version of PFENet, which is PFENet++. As I cannot find the repository of PFENet++. Thank you

**Comment by tianzhuotao** [comment]
Thanks for your interest. This is the implementation of PFENet, and our code for PFENet ++ will be released when the reviewing process is finished. Sorry for the inconvenience.
