### ISSUE TITLE
Questions about PFENet++

### ISSUE THREAD

**Issue by Sam1224** [dvlab-research/PFENet#62]
Hi, thanks for your great work!
I have three small questions about PFENet++, (1) In Eq. 5, is it an average operation or just sum? According to content later, say, the value range is within -1 and 1, I think it's average, right? (2) will the output of Eq. 9 further be processed by Eq. 4, so that the value range would be within 0 and 1? (3) is it correct that both middle-level features (after 2 1x1 convs) and high-level features are used to generate 6 prior masks (window=1, 3, 5), then the mask_add_num is set as 6 in FEM?
It would be great if the code could be released now :)

**Comment by tianzhuotao** [comment]
Yes. Both middle and high level prior masks are concatenated with features before being sent to FEM.
