### ISSUE TITLE
Questions about the backbone   

### ISSUE THREAD

**Issue by DreamerrW** [dvlab-research/PFENet#66]
hi, i'm learning your code,and i find a quesion in your PFENet.py file.

in line 204:
 if self.vgg:
                query_feat_2 = F.interpolate(query_feat_2, size=(query_feat_3.size(2),query_feat_3.size(3)), mode='bilinear', align_corners=True)

I want to ask that why the Resnet's out of conv2_layer and conv3_layer don't need interpolation to make their Feature maps the same size. 

thank you for your reply!

**Comment by tianzhuotao** [comment]
Because the ResNet has used dilated convs that make the outputs of the last three layer blocks become the same (1/8 of the input size).
